trigger:
  branches:
    include:
      - refs/tags/release-v*

pr: none

pool:
  vmImage: "macOS-15"

variables:
  - group: nuget.org

steps:
  - bash: |
      sudo xcodes select
    displayName: select solution xcode version

  - task: UseDotNet@2
    inputs:
      packageType: "sdk"
      useGlobalJson: true

  - bash: |
      echo "##vso[task.setvariable variable=bindingsVersion]$(cat Tonestro.Maui.FacebookSlim.iOS/Tonestro.Maui.FacebookSlim.iOS.csproj | grep '<Version>' | awk -F '[<>]' '{print $3}')"

  - bash: |
      echo "##vso[build.updatebuildnumber]production-tonestro-maui-facebookslim-ios-bindings-$(Build.SourceBranchName)-$(Build.BuildId)"

  - bash: |
      if [[ "$(Build.SourceBranchName)" != *"$(bindingsVersion)" ]]; then
        echo "mismatch between tag $(Build.SourceBranchName) and nuget version $(bindingsVersion)"
        exit 1
      fi

  - bash: |
      sudo dotnet workload restore
    displayName: Restore workloads

  - bash: |
      cd Tonestro.Maui.FacebookSlim.iOS
      dotnet build -c Release
      dotnet pack -c Release
    displayName: "Tonestro.Maui.FacebookSlim.iOS: Build Release Nuget"

  - bash: |
      dotnet nuget push Tonestro.Maui.FacebookSlim.iOS/nugetoutput/Tonestro.Maui.FacebookSlim.iOS.$(bindingsVersion).nupkg -k "$(nugetOrgApiKey)" -s https://api.nuget.org/v3/index.json
    displayName: "Publish nuget packages to nuget.org"

  - task: GitHubRelease@1
    inputs:
      gitHubConnection: "github.com_thisisthekap"
      repositoryName: "thisisthekap/Tonestro.Maui.FacebookSlim.iOS"
      action: "create"
      target: "$(Build.SourceVersion)"
      tagSource: "userSpecifiedTag"
      tag: "$(Build.SourceBranchName)"
      title: "Tonestro.Maui.FacebookSlim.iOS $(bindingsVersion)"
      assets: "Tonestro.Maui.FacebookSlim/nugetoutput/Tonestro.Maui.FacebookSlim.iOS.*.nupkg"
      changeLogCompareToRelease: "lastFullRelease"
      changeLogType: "issueBased"
